#!/bin/bash

source DIRECTORIES
source PARAMETERS

JOBS=$(( $THREADS / $JOBBINS ))

if [ $THREADS -ge 15 ] ; then
	TRIMCORES=4
elif [ $THREADS -ge 9 ] ; then
	TRIMCORES=2
else
	TRIMCORES=1
fi
TRIMJOBS=$JOBBINS

BWAJOBS=$JOBBINS
BWACORES=$(( $THREADS / $BWAJOBS ))
if [ $BWACORES -ge 8 ] ; then
	BWACORES=8
elif [ $BWACORES -ge 4 ] ; then
	BWACORES=4
elif [ $BWACORES -ge 2 ] ; then
	BWACORES=2
else
	BWACORES=1
fi

SAMTOOLSCORES=$(( $THREADS / $JOBBINS ))
if [ $SAMTOOLSCORES -eq 0  ] ; then
	SAMTOOLSJOBS=$THREADS
elif [ $SAMTOOLSCORES -eq 1 ] ; then
	SAMTOOLSJOBS=$JOBBINS
	SAMTOOLSCORES=0
else
	SAMTOOLSJOBS=$JOBBINS
	SAMTOOLSCORES=$(( $SAMTOOLSCORES - 1 ))
fi


echo "THREADS=$THREADS" > CORES
echo "JOBS=$JOBS" >> CORES
echo "JOBBINS=$JOBBINS" >> CORES
echo "TRIMCORES=$TRIMCORES" >> CORES 
echo "TRIMJOBS=$TRIMJOBS" >> CORES
echo "BWACORES=$BWACORES" >> CORES
echo "BWAJOBS=$BWAJOBS" >> CORES
echo "SAMTOOLSCORES=$SAMTOOLSCORES" >> CORES
echo "SAMTOOLSJOBS=$SAMTOOLSJOBS" >> CORES
