#!/bin/bash

source PARAMETERS
source PROGRAMPATHS
source DIRECTORIES

REF=$1
VCFFILEN=$VCFOUTPUTFILENAME".vcf"

VCFFILE=$VCFDIR/$VCFFILEN

echo "Creating VCF file: $VCFFILE ..."

$BCFTOOLS mpileup $BCFMPILEUPOPTIONS -f $REF $READYDIR/*.bam | $BCFTOOLS call $BCFCALLOPTIONS -o $VCFFILE

wait
echo "Done!"
echo " "

